angular.module('main',['ui.router'])
    .config(function($stateProvider){
        var main = {
            name: 'main',
            url: '/',
            templateUrl: './js/hi.html'
        }            

        var multi = {
            name: 'multi',
            url: '/multi',
            component: 'multi'
        }

        var content = {
            name: 'content',
            url: '/content',
            component: 'content'
        }

        var second = {
            name: 'second',
            url: '/second',
            template: '<h3>This routing page is generated by app.js</h3>'
        }
        

        $stateProvider.state(main);
        $stateProvider.state(multi);
        $stateProvider.state(content);
        $stateProvider.state(second);
    });
        
    